name: BE CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code in repository
        uses: actions/checkout@v4

      - name: Using Python 10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
        working-directory: starter/backend

      - name: Run lint
        run: pipenv run lint
        working-directory: starter/backend

  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code in repository
        uses: actions/checkout@v4

      - name: Using Python 10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
        working-directory: starter/backend

      - name: Testing
        run: pipenv run test
        working-directory: starter/backend

  buiding:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code in repository
        uses: actions/checkout@v4

      - name: Using Python 10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
        working-directory: starter/backend

      - name: Testing
        run: pipenv run test
        working-directory: starter/backend
