name: FE CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "starter/frontend/**"
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code in repository
        uses: actions/checkout@v4

      - name: Using Node 16
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json
          node-version: 16

      - name: Install depends
        run: npm ci
        working-directory: starter/frontend

      - name: Run lint
        run: npm run lint
        working-directory: starter/frontend

  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code in repository
        uses: actions/checkout@v4

      - name: Using Node 16
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json
          node-version: 16

      - name: Install depends
        run: npm install
        working-directory: starter/frontend

      - name: Testing
        run: npm run test
        working-directory: starter/frontend

  buiding:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code in repository
        uses: actions/checkout@v4

      - name: Using Node 16
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json
          node-version: 16

      - name: Install depends
        run: npm install
        working-directory: starter/frontend

      - name: Testing
        run: npm run test
        working-directory: starter/frontend
